# Generated by Django 4.2 on 2023-04-06 13:55

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default=None, max_length=64)),
            ],
            options={
                'db_table': 'django_jsonapi_framework__organizations',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.CharField(default=None, max_length=254, validators=[django.core.validators.EmailValidator(allowlist=[])])),
                ('password_hash', models.CharField(default=None, max_length=254)),
                ('organization', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='django_jsonapi_framework.organization')),
            ],
            options={
                'db_table': 'django_jsonapi_framework__users',
            },
        ),
        migrations.AddField(
            model_name='organization',
            name='owner',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='django_jsonapi_framework.user'),
        ),
    ]
