# Generated by Django 4.2 on 2023-04-12 10:37

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django_model_signals.transceiver
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default=None, max_length=64)),
            ],
            options={
                'db_table': 'django_jsonapi_framework__auth__organizations',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('is_email_confirmed', models.BooleanField(default=False)),
                ('organization', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='django_jsonapi_framework__auth.organization')),
            ],
            options={
                'db_table': 'django_jsonapi_framework__auth__users',
            },
            bases=(django_model_signals.transceiver.ModelSignalsTransceiver, 'auth.user'),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='organization',
            name='owner',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='django_jsonapi_framework__auth.user'),
        ),
    ]
